---
title: "Modelos Lineares"
author: "Prof. Dr. Juliano Bortolini"
date: ""
output: html_document
---

*Bacharelado em Estatística - UFMT*

*Período letivo: 2024/1*


### Avisos:
- Última atualização do site às **`r format(Sys.time(), "%H:%M", tz='America/Cuiaba')`** do dia **`r format(Sys.time(), "%d/%m/%Y")`**.
- Monitores: Aline e Marcos
- [Whatsapp da disciplina](https://chat.whatsapp.com/GgdG61qLafrJJxNarlwvOF)
- Prova 1 disponível no [portal acadêmico](https://sistemas.ufmt.br/ufmt.portalsistemas). Data de entrega: 19/8/2024. **A prova será remota**.
- Prova 2 disponível no [portal acadêmico](https://sistemas.ufmt.br/ufmt.portalsistemas). Data de entrega: 7/10/2024 até às 23h. **A prova será remota**.
- Prova 3 disponível no [portal acadêmico](https://sistemas.ufmt.br/ufmt.portalsistemas). Data de entrega: 28/10/2024 até às 23:59. **A prova será remota**.

### Ementa:

Álgebra de matrizes. Inversas generalizadas e soluções de sistemas. Vetores e matrizes aleatórios. Distribuição de formas lineares e quadráticas de vetores aleatórios. Modelos lineares: Caracterização, estimação por mínimos quadrados, sistema de equações normais. Modelos lineares com restrições nas soluções e nos parâmetros. Tipos de soma de quadrados.


### Notas de aula:

- [Aula 1](aulas/aula1.html): apresentação da disciplina e ideias gerais sobre teoria de matrizes e modelos lineares.

- [Aula 2](aulas/aula2.html): definições de matrizes.

- [Aula 3](aulas/aula3.html): teoremas sobre matrizes e vetores. Operações entre matrizes e vetores.

- Lista 1: capítulo 2 do livro do Rencher.

- [Aula 4](aulas/aula4.html): formas quadráticas e bilineares, vetores LI e LD, posto de uma matriz, matriz inversa, matriz positiva definida e semidefinida.

- [Aula 5](aulas/aula5.html): inversa generalizada, sistemas de equações e teoremas. Prova daqui 2 aulas.

- [Aula 6](aulas/aula6.html): inversa generalizada e sistemas de equações, vetores e matrizes ortogonais, traço de uma matriz, autovalor e autovetor, matriz idempotente e cálculo com funções de vetores e matrizes.

- Aula 7: Avaliação A1 disponível no [portal acadêmico](https://sistemas.ufmt.br/ufmt.portalsistemas). Conteúdo da prova: álgebra de matrizes, inversas generalizadas e soluções de sistemas lineares.

- Aula 8: refazer a avaliação A1 com data de entrega 2/9/2024.

- Aula 9: vetores e matrizes aleatórios (capítulo 3 do livro do Rencher) e distribuição normal uni e multivariada (capítulo 4).

- Aula 10: exercícios sobre vetores e matrizes aleatórios e distribuição normal multivariada. Exercícios dos capítulos 3 e 4 do livro do Rencher. 

- Aula 11: distribuição de formas lineares e quadráticas de vetores aleatórios. Capítulo 5 do livro do Rencher.

- [Tarefa](tarefap2.html): exercícios sobre vetores e matrizes aleatórios, distribuição normal multivariada e distribuição de formas lineares e quadráticas de vetores aleatórios. Pontuação: 2 pontos extras na A2. Data de entrega: 7/10/2024, juntamente com A2.

- Aula 12: modelos lineares (posto completo): estimaçao em regresão linear simples e múltipla. Capítulos 6 e 7 do livro do Rencher.

- Aula 13: Avaliação A2 disponível no [portal acadêmico](https://sistemas.ufmt.br/ufmt.portalsistemas). Conteúdo da prova: vetores e matrizes aleatórios, distribuição normal multivariada e distribuição de formas lineares e quadráticas de vetores aleatórios. Data de entrega: 7/10/2024 até as 23h. **A prova será remota**.

- Aula 14: um pouco mais sobre modelos lineares (posto completo): estimaçao em regresão linear simples e múltipla. Capítulos 6 e 7 do livro do Rencher.

- Aula 15: modelos lineares (posto incompleto): capítulo 12 do livro do Rencher.

- Aula 16: Avaliação A3: exercícios 6.1, 6.2, 6.3, 6.5, 6.6, 6.10, 6.14 (a), 7.1, 7.11, 7.53 (a), 7.53 (d), 7.54 (a), 7.54 (c), 7.55 (a) e 7.55 (c), do livro Linear Models in Statistics, do Rencher. Data de entrega: 28/10/2024 até as 23:59 no AVA.


### Avaliação:


*Os critérios de avaliação seguem a Resolução CONSEPE 63/2018.*


3 avaliações (com pontuação de 0 a 10):

  - A1: álgebra de matrizes, inversas generalizadas e soluções de sistemas lineares.
  - A2: vetores e matrizes aleatórios, distribuição normal multivariada e distribuição de formas lineares e quadráticas de vetores aleatórios.
  - A3: modelos lineares e seus pressupostos, estimação por mínimos quadrados, sistemas de equações normais, modelos lineares com restrições nas soluções e parâmetros e os diferentes tipos de soma de quadrados.
  
O aluno que tiver a nota final, definida pela média aritmética das notas das 3 avaliações, maior ou igual a 5 estará aprovado. **Não há prova final.**

Faltas superiores a 16 horas (equivalente a 4 aulas) implicam em reprovação por falta.

Solicitações de segunda chamada para as provas serão avaliadas conforme o disposto no art. 80 da Res. Consepe nº 14/1999 e art. 8º da Res. Consepe nº 27/1999. Clique [aqui](https://ufmt.br/unidade/estudante/graduacao/pagina/requerimentos/188) para mais informações sobre segunda chamada.

### Livro texto:

RENCHER, Alvin C.; SCHAALJE, G. Bruce. **Linear models in statistics.** John Wiley & Sons. 2008.



----------
<div style="text-align: center;">

[@profjulianobortolini](https://instagram.com/profjulianobortolini) \  \  \ [www.julianobortolini.com.br](http://www.julianobortolini.com.br) \  \  \ [linkedin](https://linkedin.com/in/julianobortolini) \  \  \ [github](https://github.com/julianobortolini) \  \  \  [lattes](http://lattes.cnpq.br/6210909768845403)

</div>







