---
title: "Modelos Lineares"
author: "Prof. Dr. Juliano Bortolini"
output: html_document
---

*Bacharelado em Estatística - UFMT*

*Período letivo: 2024/1*

Última atualização do site às **`r format(Sys.time(), "%H:%M")`** do dia **`r format(Sys.time(), "%d/%m/%Y")`**.

[**Página inicial**](../index.html)

**Aula 4: 29-7-2024**

- Capítulo 2 do livro do Rencher.
- Revisão da aula passada: Teoremas sobre matrizes e vetores.
- Formas quadráticas e bilineares.
- Aplicações de formas quadráticas na estatística.
- Produto de duas matrizes: elemento a elemento ou Hadamard.
- Partição de matrizes em submatrizes.
- Exemplos de partição de matrizes.
- Produto usual de matrizes (particionadas).
- Partição de matrizes em vetores com elementos sendo vetores linhas ou colunas.
- Vetores linearmente independentes e dependentes.
- Posto (ou Rank) de uma matriz.
- Teorema (teorema 2.4) sobre posto do produto de duas matrizes.
- Matriz inversa.
- Teorema 2.5a e b.
- Matriz positiva definida e semidefinida.
- Qualquer forma quadrática pode ser escrita com uma matriz simétrica e única.
- Lista 1: capítulo 2 do livro do Rencher.

Sugestão de leitura: RENCHER, Alvin C.; SCHAALJE, G. Bruce. **Linear models in statistics.** John Wiley & Sons. 2008.


----------
<div style="text-align: center;">

[@profjulianobortolini](https://instagram.com/profjulianobortolini) \  \  \ [www.julianobortolini.com.br](http://www.julianobortolini.com.br) \  \  \ [linkedin](https://linkedin.com/in/julianobortolini) \  \  \ [github](https://github.com/julianobortolini) \  \  \  [lattes](http://lattes.cnpq.br/6210909768845403)

</div>





  
  
  